### PR TITLE
Unable to start server axios missing -- Installed axios

### PR DESCRIPTION
**Pull request by mwave317**

### CODE REVIEW

**Comment by AtnNn** [comment]
Thanks for pointing out the missing `axios`.

`axios` is a dependency of `vuetable-2`. A proper fix would be to update `npm-shrinkwrap.json`.

**Comment by mwave317** [comment]
Ok, I'll work on it

**Comment by mwave317** [comment]
I made the changes to the npm-shrinkwrap.json file. The change starts at line 208. Thanks

**Comment by AtnNn** [comment]
Sorry, perhaps I wasn't clear. `axios` should not be added to `package.json` because we don't use it directly. I believe it is a transitive dependency of `vuetable-2`. Perhaps something like `npm install --save vuetable-2` might re-create the `npm-shrinkwrap.json` file correctly.

**Comment by mwave317** [comment]
Ok, I’ll work on it. I tried your suggestion but both files still list axios, as they did previously.

Thanks,

**Comment by AndrewNatoli** [comment]
This _should_ be resolvable by simply running `npm install --save axios` so long as you are running at least Node 7.9.0.

I'd recommend undoing any manual changes to your `npm-shrinkwrap` and `package` files; the `--save` flag will make npm write the appropriate file changes for you.

**Comment by AndrewNatoli** [comment]
Resolved in 4354d65640f673665e2de8653dc7d756749b8483

**Pull request closed without merging**
