### PR TITLE
Registration & authentication

### PR DESCRIPTION
**Pull request by chimon2000**
- [x] Add v2 firebase authentication
- [x] Add registration / authentication client
- [x] Update auth guard to verify app & claims
- [x] Add per app claims 
- [x] Add login redirect to referrer

### CODE REVIEW

**Comment by AndrewNatoli** [comment]
@chimon2000 Running locally I was able to get an auth token to register, and when I filled out the registration form I got:

```
{
  "error": {
    "code": 400,
    "message": "MISSING_EMAIL",
    "errors": [
      {
        "message": "MISSING_EMAIL",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}
```
when submitting the registration. Ever run into this?

**Comment by chimon2000** [comment]
@AndrewNatoli is this error happening when you hit the auth app?

**Comment by AndrewNatoli** [comment]
@chimon2000 Yeah, it was when trying to submit the registration form in the auth app

**Comment by AndrewNatoli** [comment]
@chimon2000 - Auth app falls into an infinite redirect loop when you run it using `yarn start-client` from the project root. If you run the app individually though it seems to work..

**Comment by AndrewNatoli** [comment]
We'll also need a custom email handler 

https://firebase.google.com/docs/auth/custom-email-handler

"You can now sign in with your new account" unfortunately isn't something valid to show our users since they need to be approved. :(

**Comment by chimon2000** [comment]
Good point, do we want to do that as part of this PR @AndrewNatoli ?

**Comment by chimon2000** [comment]
A few things missing from this PR:

- [ ] Change auth from an app to a "mini-app" that can be plugged into any app

- [ ] Get rid of server, each app is expected to use auth mini-app

- [ ] `setCustomUserClaims` should set the **app** + **role** the user has access to.

**Pull request merged**
